### ISSUE TITLE
Recommendation for readme.md

### ISSUE THREAD

**Issue by bradpoulton** [maerteijn/SaltGUI#9] opened 2018-03-29 05:51 UTC
Can you change this:

  port: 8000
  host: 0.0.0.0
  disable_ssl: true
  app: /srv/salt-gui/index.html
  static: /srv/salt-gui/static
  static_path: /static

to this:

  port: 8000
  host: 0.0.0.0
  disable_ssl: true
  app: /srv/saltgui/index.html
  static: /srv/saltgui/static
  static_path: /static

in your readme.md file? The default folder name is saltgui when pulled down with git clone. Thanks

**Comment by erwindon** [comment] 2018-05-13 14:42
I've added a PR to fix this

**Comment by maerteijn** [comment] 2018-05-14 11:27
Duplicate of  #8

**Closed by maerteijn** 2018-05-14 11:27 UTC
